# Generated by Django 4.1.2 on 2022-10-21 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lista_De_Tarefas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefas',
            name='datas',
            field=models.CharField(max_length=10),
        ),
    ]
